name: Elixir CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    container:
      image: hexpm/elixir:1.18.2-erlang-27.2.2-debian-bullseye-20250203-slim

    steps:
      - uses: actions/checkout@v4

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Dependency Packages
        run: |
          apt-get update -y && apt-get install -y build-essential inotify-tools git

      - name: Setup Elixir Tools
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check Code Format
        run: mix format --check-formatted

      - name: Credo Checks
        run: |
          mix credo

      - name: Run tests with warnings as errors
        run: |
          mix deps.compile
          mix compile --warnings-as-errors
          mix test --warnings-as-errors
